export const projects = [
  {
    slug: 'apple-concept-ad',
    no: '01',
    name: 'Apple Concept AD',
    meta: 'Brand film - Concept',
    classification: 'Independent concept',
    year: '2026',
    art: 'apple',
    mediaKey: 'apple-concept-ad',
    platforms: 'YouTube - Social - Portfolio',
    thesis: 'A polished concept advertisement exploring Apple through clarity, restraint and product-led emotion.',
    context: 'Apple communication is known for making technology feel simple, personal and desirable. This independent concept studies that language without presenting itself as commissioned work for Apple.',
    direction: 'The film leans into clean pacing, minimal messaging and a premium visual rhythm, using restraint to make the product idea feel more confident and memorable.',
    contribution: 'Concept - Script - Creative direction - AI production - Post-production',
    outcome: 'Independent portfolio concept. No Apple client relationship or performance claim is attached.'
  },
  {
    slug: 'penrose-skin',
    no: '02',
    name: 'Penrose Skin',
    meta: 'Paid social - Claymation',
    classification: 'Selected prior work',
    year: '2026',
    art: 'penrose',
    mediaKey: 'penrose-claymation',
    platforms: 'Meta - TikTok - Website',
    thesis: 'A tactile product story designed to interrupt the polished sameness of a social feed.',
    context: 'Penrose Skin creates fragrance-inspired body butters that combine designer-inspired scent with daily moisturisation. The creative problem was to communicate lasting fragrance, skincare value and a vegetarian formulation without falling into conventional beauty advertising.',
    direction: 'Claymation gave the product a playful physical presence and a distinctive visual category within paid social. The film was structured to make the product difference understandable quickly while retaining enough novelty to hold attention.',
    contribution: 'Creative strategy - Script - Creative direction - AI production - Post-production - Music and SFX',
    outcome: 'Approved for use. Performance figures can be added when publication is cleared.'
  },
  {
    slug: 'memzero-launch',
    no: '03',
    name: 'MemZero',
    meta: 'SaaS - Product launch',
    classification: 'Selected prior work',
    year: '2026',
    art: 'memzero',
    mediaKey: 'memzero-launch',
    platforms: 'Product launch - Brand channels',
    thesis: 'A sarcastic launch film introducing an AI memory agent without conventional software-demo language.',
    context: 'MemZero is an AI memory product developed by Gateway. The objective was to communicate what the agent does in roughly thirty seconds while creating an opening strong enough to earn attention.',
    direction: 'Humour, pacing and clarity introduce the product through a memorable narrative rather than a feature-heavy explanation.',
    contribution: 'Concept - Script - Creative direction - AI production - Post-production',
    outcome: 'Selected draft work. Final publication status should be confirmed before launch.'
  },
  {
    slug: 'bella-necklace-ad',
    no: '04',
    name: 'Bella Necklace',
    meta: 'Jewellery - Short-form ad',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'bella',
    mediaKey: 'bella-necklace-ad',
    platforms: 'YouTube Shorts - Social',
    thesis: 'A concise vertical product film designed to give the Bella necklace an elegant, attention-led presence.',
    context: 'The short-form format called for a product story that could establish mood and desirability immediately on a mobile screen.',
    direction: 'Premium product imagery and deliberate pacing keep the necklace central while building a polished visual identity around it.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'vyve-coffee-ad',
    no: '05',
    name: 'Vyve Coffee / 01',
    meta: 'Food and beverage - Short-form ad',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'vyve',
    mediaKey: 'vyve-coffee-ad',
    platforms: 'YouTube Shorts - Social',
    thesis: 'A sensory coffee advertisement built for fast, vertical viewing.',
    context: 'Coffee creative needs to make taste, texture and ritual feel immediate without relying on a long product explanation.',
    direction: 'Close product detail, momentum and atmosphere turn a familiar daily ritual into a compact brand moment.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'accidentclaim-claymation-ad',
    no: '06',
    name: 'Accident Claim',
    meta: 'Claymation - Short-form ad',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'accidentclaim',
    mediaKey: 'accidentclaim-claymation-ad',
    platforms: 'YouTube Shorts - Social',
    thesis: 'A claymation-led advertisement that makes a practical service feel approachable and visually distinct.',
    context: 'Claims advertising often uses familiar category conventions, creating an opportunity for a more tactile and memorable treatment.',
    direction: 'A playful claymation language softens the subject matter and creates a clear visual interruption in a short-form feed.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'vyve-coffee-ad-2',
    no: '07',
    name: 'Vyve Coffee / 02',
    meta: 'Food and beverage - Short-form ad',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'vyve',
    mediaKey: 'vyve-coffee-ad-2',
    platforms: 'YouTube Shorts - Social',
    thesis: 'A second vertical coffee study exploring another visual route for the same product category.',
    context: 'Multiple creative routes allow a brand to test different expressions while retaining a recognisable product focus.',
    direction: 'This variation shifts the rhythm and imagery while preserving the sensory appeal at the centre of the campaign.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'lovify-music-app-ad',
    no: '08',
    name: 'Lovify',
    meta: 'Music app - Short-form ad',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'lovify',
    mediaKey: 'lovify-music-app-ad',
    platforms: 'YouTube Shorts - Social',
    thesis: 'A fast-moving music-app advertisement shaped around energy, emotion and mobile-first pacing.',
    context: 'A music product has to communicate feeling as quickly as function when it appears in a short-form feed.',
    direction: 'Rhythmic editing and expressive visuals position the app as an experience rather than a conventional software demonstration.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'penrose-ugc-car',
    no: '09',
    name: 'Penrose UGC Car',
    meta: 'UGC - Product advertisement',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'penrose',
    mediaKey: 'penrose-ugc-car',
    platforms: 'YouTube - Social',
    thesis: 'A creator-style Penrose product film built around a direct, everyday setting.',
    context: 'The objective was to give the product a natural social presence while keeping the message immediate and easy to follow.',
    direction: 'A casual in-car setup and direct delivery make the creative feel native to the feed without losing the product focus.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'rovina-softgels-ad',
    no: '10',
    name: 'Rovina Softgels',
    meta: 'Wellness - Product advertisement',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'rovina',
    mediaKey: 'rovina-softgels-ad',
    platforms: 'YouTube - Social',
    thesis: 'A concise product advertisement giving Rovina Softgels a clear, polished wellness presence.',
    context: 'The creative needed to introduce the product quickly while maintaining a credible and approachable visual tone.',
    direction: 'Clean product emphasis and controlled pacing keep the message understandable within a compact social format.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'peggy-summer-camp-ad',
    no: '11',
    name: 'Peggy Summer Camp',
    meta: 'Campaign - Product advertisement',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'peggy',
    mediaKey: 'peggy-summer-camp-ad',
    platforms: 'YouTube - Social',
    thesis: 'An energetic Peggy advertisement shaped around the playful world of a summer-camp mission.',
    context: 'The campaign idea called for an immediately recognisable setting with enough character to hold attention in a fast feed.',
    direction: 'Playful narrative cues and lively pacing turn the product message into a compact, story-led creative moment.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'snatched-jawline-ad',
    no: '12',
    name: 'Snatched the Jawline',
    meta: 'Beauty - Product advertisement',
    classification: 'Selected short-form work',
    year: '2026',
    art: 'jawline',
    mediaKey: 'snatched-jawline-ad',
    platforms: 'YouTube - Social',
    thesis: 'A beauty advertisement built around a direct visual transformation hook.',
    context: 'The format needed to communicate the central benefit immediately while remaining visually engaging and easy to understand.',
    direction: 'A clear opening hook, focused imagery and fast pacing make the core idea legible within seconds.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected short-form portfolio work.'
  },
  {
    slug: 'tooth-truth-ad',
    no: '13',
    name: 'Tooth Truth',
    meta: 'Dental care - Advertisement',
    classification: 'Selected portfolio work',
    year: '2026',
    art: 'tooth-truth',
    mediaKey: 'tooth-truth-ad',
    platforms: 'YouTube - Social - Portfolio',
    thesis: 'A direct dental-care advertisement designed to turn a practical message into an engaging visual story.',
    context: 'The communication challenge was to make a familiar health topic feel clear, watchable and relevant without overcomplicating it.',
    direction: 'A strong premise and controlled narrative progression carry the audience from attention to understanding.',
    contribution: 'Creative direction - AI production - Post-production',
    outcome: 'Selected portfolio work.'
  }
]

export const services = [
  ['Brand strategy & identity', 'Clarify the story, position and creative territory a brand can own.'],
  ['Performance creative strategy', 'Diagnose the communication problem and develop distinct angles for paid social.'],
  ['Scripts & creative angles', 'Build hooks, narratives and variations around one clear strategic truth.'],
  ['AI-native ad production', 'Turn approved directions into modern, platform-ready advertising creative.']
]
